version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Branch-SDK/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Branch-SDK/build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Test
          command: ./gradlew test
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: ./Branch-SDK/build/outputs/aar/