name: appium-automation
on: push
env:
  ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  BROWSERSTACK_USER: ${{ secrets.BROWSER_STACK_USER }}
  BROWSERSTACK_KEY: ${{ secrets.BROWSER_STACK_KEY }}
jobs:  
  appium-automation-tests:
    name: appium-automation-tests
    runs-on: macos-latest
    steps:
      - name: Checkout SDK repo with testbed app
        uses: actions/checkout@v3
        with:
          path: sdk 
      - name: Checkout qa automation
        uses: actions/checkout@v3
        with:
          path: qa
          repository: BranchMetrics/qentelli-saas-sdk-testing-automation
          ref: gdeluna-branch/FixBrace
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
        # repo's gradle is configured to run on java 11
      - name: Setup java 11 for gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      # to reduce complexity, testbed app uses sdk as a project reference
      - name: Build testbed app
        run: |
          cd sdk
          ./gradlew Branch-SDK-Automation-TestBed:assembleDebug
      # copy over testbed apk to the automation input apk folder
      - name: Copy APK to QA
        run: |
          mkdir -p qa/testdata/builds_new/
          cp sdk/Branch-SDK-Automation-TestBed/build/outputs/apk/debug/Branch-SDK-Automation-TestBed-debug.apk qa/testdata/builds_new/Branch-SDK-Automation-TestBed-debug.apk
      - name: Execute automation
        run: |
          cd qa
          mvn clean test -DsuiteXMLFile=testng.xml -e -DInputFormat="json" -DInputFilePath="TestSelection_BrowserStack_Android.json" -DUploadNewBuild="Yes"
