name: appium-automation
on: push
jobs:  
  appium-automation-tests:
    name: appium-automation-tests
    runs-on: macos-latest
    steps:
      - name: Checkout SDK repo with testbed app
        uses: actions/checkout@v3
        with:
          path: sdk 
      - name: Checkout qa repository
        uses: actions/checkout@v3
        with:
          path: qa
          repository: BranchMetrics/qentelli-saas-sdk-testing-automation
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
        # repo's gradle is configured to run on java 11
      - name: Setup java 11 for gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      # to reduce complexity, testbed app uses sdk as a project reference
      - name: Build testbed app
        run: |
          echo "$PWD"
          ls
          cd sdk
          ls
          ./gradlew Branch-SDK-Automation-TestBed:assembleDebug
          ls ./Branch-SDK-Automation-TestBed/build/outputs/apk/debug/
      # copy over test bed apk with sdk
      - name: Copy testbed apk
        run: |
          echo "$PWD"
          ls
          mkdir -p qa/testdata/builds_new/
          cp sdk/Branch-SDK-Automation-TestBed/build/outputs/apk/debug/Branch-SDK-Automation-TestBed-debug.apk qa/testdata/builds_new/Branch-SDK-Automation-TestBed-debug.apk
      - name: Execute automation
        run: |
          echo "$PWD"
          cd qa
          ls
          mvn clean test -DsuiteXMLFile=testng.xml -e -DInputFormat="json" -DInputFilePath="TestSelection_BrowserStack_Android.json" -DAccessKey="${ACCESS_KEY}" -DSecretKey="${SECRET_KEY}" -DBROWSERSTACK_USER="${BROWSERSTACK_USER}" -DBROWSERSTACK_KEY="${BROWSERSTACK_KEY}" -DUploadNewBuild="Yes"
      - name: Print output
        if: success() || failure()        # run this step even if previous step failed
        run: cat output.txt
      - name: Publishing test report
        if: success() || failure()        # run this step even if previous step failed
        uses: actions/upload-artifact@v3  # upload test results
        with:
          name: test-results
          path: output.txt
