name: appium-automation
on: push
jobs:  
  retrieveAutomationJar:
    runs-on: macos-latest
    steps:
      - name: Checkout qa repository
        uses: actions/checkout@v3
        with:
          repository: BranchMetrics/qentelli-saas-sdk-testing-automation
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
          path: qa-repo
      - name: Execute automation
        run: |
          cd qa-repo
          ls
