name: appium-automation
on: push
jobs:  
  runs-on: macos-latest
  build-and-run-automation:
    steps:
      - name: Checkout SDK repo with testbed app
        uses: actions/checkout@v3
        # repo's gradle is configured to run on java 11
      - name: Setup java 11 for gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      # to reduce complexity, testbed app uses sdk as a project reference
      - name: Build testbed app
        run: |
          ./gradlew Branch-SDK-Automation-TestBed:assembleDebug
          ls /Branch-SDK-Automation-TestBed/build/outputs/apk/debug/
      # checkout qa automation
      - name: Checkout qa repository
        uses: actions/checkout@v3
        with:
          repository: BranchMetrics/qentelli-saas-sdk-testing-automation
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
          path: qa-repo
      - name: Execute automation
        run: |
          cd qa-repo
          ls
