name: appium-automation
on: push
jobs:  
  retrieveAutomationJar:
    runs-on: macos-latest
    steps:
      - name: List Releases
        #expecting this to be empty
        run: gh release list --repo BranchMetrics/qentelli-saas-sdk-testing-automation
        env:
          GITHUB_TOKEN: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
      - name: Fetch asset
        run: gh release download --repo BranchMetrics/qentelli-saas-sdk-testing-automation 0.0.1-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
      - name: List content
        run: ls
